export E2E_ADMIN_EMAIL="admin@test.com"
export E2E_ADMIN_PASSWORD="password"
export E2E_GUEST_EMAIL="guest@test.com"
export E2E_GUEST_PASSWORD="password"
export SUPABASE_URL="https://ci_dummy.supabase.co"
export SUPABASE_SERVICE_ROLE_KEY="ci_dummy_key"
export NEXT_PUBLIC_FIREBASE_API_KEY="ci_dummy_api_key"
export NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="ci_dummy.firebaseapp.com"
export NEXT_PUBLIC_FIREBASE_PROJECT_ID="ci_dummy_project"
export NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="ci_dummy_bucket"
export NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="1234567890"
export NEXT_PUBLIC_FIREBASE_APP_ID="1:123:web:ci_dummy"
npx playwright test e2e/playwright/smoke.spec.ts --retries=1 --reporter=list
