// @ts-nocheck
import { verifyUser } from '@/lib/server-utils';
import { NextRequest, NextResponse } from 'next/server';
import { supabase } from '@/lib/supabaseClient';
import { logEventUpdated, logTaskCreated } from '@/app/api/_lib/audit';
import { FEATURE_FLAGS } from '@/config/featureFlags';

/**
 * POST /api/events/[id]/approve
 * Approve or decline event (admin only)
 * Body: { action: 'approve' | 'decline' }
 */

export const dynamic = 'force-dynamic';

export async function POST(
  req: NextRequest,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const user = await verifyUser(req);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Only admin can approve/decline events
    if (user.role !== 'admin') {
      return NextResponse.json(
        { error: 'Only admins can approve or decline events' },
        { status: 403 }
      );
    }

    const { id } = await context.params;

    // Check if event exists
    const { data: eventData, error: eventError } = await supabase
      .from('events')
      .select('*')
      .eq('id', id)
      .single();

    if (eventError || !eventData) {
      return NextResponse.json({ error: 'Event not found' }, { status: 404 });
    }

    const body = await req.json();
    const { action } = body;

    if (!action || !['approve', 'decline'].includes(action)) {
      return NextResponse.json(
        { error: 'Action must be either "approve" or "decline"' },
        { status: 400 }
      );
    }

    const status = action === 'approve' ? 'approved' : 'declined';
    const now = new Date().toISOString();

    // Update the event
    const { error: updateError } = await supabase
      .from('events')
      .update({
        status,
        updated_at: now,
      })
      .eq('id', id);

    if (updateError) throw updateError;

    // Log audit event
    await logEventUpdated(
      user.uid,
      user.tenantId || 1,
      id as any,
      { action: 'approval', status: status }
    );

    // Event-to-Task Automation: Create predefined tasks when event is approved
    if (FEATURE_FLAGS.EVENT_TASK_AUTOMATION && status === 'approved') {
      try {
        // Check if tasks already exist for this event to prevent duplicates
        const { data: existingTasks, error: taskCheckError } = await supabase
          .from('tasks')
          .select('id')
          .eq('event_id', id)
          .eq('autoGenerated', true);

        // Only create tasks if none exist yet
        if (!taskCheckError && (!existingTasks || existingTasks.length === 0)) {
          const startTime = eventData.start_at || eventData.startTime;
          const eventDate = new Date(startTime);

          // Define the automated tasks
          const automatedTasks = [
            {
              title: 'Event Shoot',
              description: `Photography/Videography for event: ${eventData.title}`,
              due_date: eventDate.toISOString(),
              priority: 'medium'
            },
            {
              title: 'Photo Editing',
              description: `Post-processing for event photos: ${eventData.title}`,
              due_date: new Date(eventDate.getTime() + 24 * 60 * 60 * 1000).toISOString(), // +1 day
              priority: 'medium'
            },
            {
              title: 'Video Highlights',
              description: `Create video highlights for event: ${eventData.title}`,
              due_date: new Date(eventDate.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(), // +2 days
              priority: 'medium'
            }
          ];

          // Create each automated task
          for (const taskDefinition of automatedTasks) {
            const taskData: any = {
              ...taskDefinition,
              event_id: id,
              institution_id: eventData.institution_id || user.institution_id,
              status: 'pending',
              autoGenerated: true, // Flag to identify auto-generated tasks
              created_by: {
                uid: user.uid,
                role: user.role
              },
              created_at: new Date().toISOString(),
              updated_at: new Date().toISOString()
            };

            const { data: newTask, error: createError } = await supabase
              .from('tasks')
              .insert(taskData)
              .select()
              .single();

            if (!createError && newTask) {
              // Log audit event for each auto-created task
              await logTaskCreated(
                user.uid,
                user.tenantId || 1,
                newTask.id,
                {
                  title: taskDefinition.title,
                  event_id: id,
                  autoGenerated: true,
                  description: 'Auto-created task from event approval automation'
                }
              );
            }
          }
          // Note: Legacy ServerNotification broadcast removed to maintain architecture lean
        }
      } catch (automationError) {
        console.error('Error in event-to-task automation:', automationError);
      }
    }

    // Return the updated event
    const updatedEvent = { id, ...eventData, status, updated_at: now };
    return NextResponse.json({ data: updatedEvent }, { status: 200 });
  } catch (error) {
    console.error('[POST /api/events/[id]/approve]', error);
    return NextResponse.json(
      { error: 'Failed to update event approval status' },
      { status: 500 }
    );
  }
}
