import { NextRequest, NextResponse } from 'next/server';
import { getFirebaseServices, verifyUser } from '@/lib/server-utils';
import { logEventUpdated, logTaskCreated } from '@/app/api/_lib/audit';
import { FEATURE_FLAGS } from '@/config/featureFlags';
import { ServerNotification } from '@/lib/server-notification';

/**
 * POST /api/events/[id]/approve
 * Approve or decline event (admin only)
 * Body: { action: 'approve' | 'decline' }
 */
export async function POST(
  req: NextRequest,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const { firestore } = await getFirebaseServices();
    const user = await verifyUser(req);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Only admin can approve/decline events
    if (user.role !== 'admin') {
      return NextResponse.json(
        { error: 'Only admins can approve or decline events' },
        { status: 403 }
      );
    }

    const { id } = await context.params;

    // Check if event exists
    const eventDoc = await firestore.collection('events').doc(id).get();
    if (!eventDoc.exists) {
      return NextResponse.json({ error: 'Event not found' }, { status: 404 });
    }

    const eventData = eventDoc.data()!;

    const body = await req.json();
    const { action } = body;

    if (!action || !['approve', 'decline'].includes(action)) {
      return NextResponse.json(
        { error: 'Action must be either "approve" or "decline"' },
        { status: 400 }
      );
    }

    const status = action === 'approve' ? 'approved' : 'declined';
    const now = new Date().toISOString();

    // Update the event
    await firestore.collection('events').doc(id).update({
      status,
      updatedAt: now,
    });

    // Log audit event
    await logEventUpdated(
      user.uid,
      user.tenantId || 1,
      id as any,
      { action: 'approval', status: status }
    );

    // Event-to-Task Automation: Create predefined tasks when event is approved
    if (FEATURE_FLAGS.EVENT_TASK_AUTOMATION && status === 'approved') {
      try {
        // Check if tasks already exist for this event to prevent duplicates
        const existingTasksSnapshot = await firestore
          .collection('tasks')
          .where('eventId', '==', id)
          .where('autoGenerated', '==', true)
          .get();

        // Only create tasks if none exist yet
        if (existingTasksSnapshot.empty) {
          const eventDate = new Date(eventData.startTime);

          // Define the automated tasks
          const automatedTasks = [
            {
              title: 'Event Shoot',
              description: `Photography/Videography for event: ${eventData.title}`,
              dueDate: eventDate.toISOString(),
              priority: 'medium'
            },
            {
              title: 'Photo Editing',
              description: `Post-processing for event photos: ${eventData.title}`,
              dueDate: new Date(eventDate.getTime() + 24 * 60 * 60 * 1000).toISOString(), // +1 day
              priority: 'medium'
            },
            {
              title: 'Video Highlights',
              description: `Create video highlights for event: ${eventData.title}`,
              dueDate: new Date(eventDate.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(), // +2 days
              priority: 'medium'
            }
          ];

          // Create each automated task
          const createdTasks = [];
          for (const taskDefinition of automatedTasks) {
            const taskData: any = {
              ...taskDefinition,
              eventId: id,
              institutionId: eventData.institutionId || user.institutionId || '1',
              status: 'pending',
              autoGenerated: true, // Flag to identify auto-generated tasks
              createdBy: {
                uid: user.uid,
                role: user.role
              },
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString()
            };

            const taskRef = await firestore.collection('tasks').add(taskData);
            createdTasks.push({ id: taskRef.id, ...taskData });

            // Log audit event for each auto-created task
            await logTaskCreated(
              user.uid,
              user.tenantId || 1,
              taskRef.id,
              {
                title: taskDefinition.title,
                eventId: id,
                autoGenerated: true,
                description: 'Auto-created task from event approval automation'
              }
            );
          }

          // Send notification to admins
          const adminIds = await ServerNotification.getAdminIds();
          if (adminIds.length > 0) {
            await ServerNotification.broadcast(adminIds, {
              type: 'event_updated',
              title: 'Media Tasks Auto-Created',
              message: `Media tasks auto-created for approved event: ${eventData.title}`,
              entityType: 'event',
              entityId: id,
              sourceUserId: user.uid,
              priority: 'medium'
            });
          }
        }
      } catch (automationError) {
        console.error('Error in event-to-task automation:', automationError);
        // Don't fail the approval if automation fails
      }
    }

    // Return the updated event
    const updatedEvent = { id, ...eventData, status, updatedAt: now };
    return NextResponse.json({ data: updatedEvent }, { status: 200 });
  } catch (error) {
    console.error('[POST /api/events/[id]/approve]', error);
    return NextResponse.json(
      { error: 'Failed to update event approval status' },
      { status: 500 }
    );
  }
}
