-- Migration: 20260306_tasks_upgrade.sql
-- Goal: Stabilize Tasks Table with missing columns used in API and UI

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'medium';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS due_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS assigned_to JSONB DEFAULT '[]';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'general';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS is_archived BOOLEAN DEFAULT false;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT false;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS institution_id INTEGER;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS department_id INTEGER;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS tenant_id INTEGER;
